inherit_gem:
  paperkite-rubocop: config/base.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/rails_app/**/*
    - bin/*
    - Rakefile

Naming/FileName:
  Exclude:
    - lib/remote-config.rb
