name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
      - epic/*

jobs:

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: 1.14.0
          rubocop_extensions: rubocop-rails:2.10.1 rubocop-performance:1.11.2 rubocop-rspec:2.3.0
          reporter: github-pr-review
          use_bundler: true

  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.5.8, 2.7.4, 3.0.1, 3.1.1]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run RSpec
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:test:prepare
          bundle exec rspec
